
version: '3.8'

services:
  web:
    build: .
    volumes:
      - app-data:/app/data
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=sqlite:///app/data/visitors.db
    networks:
      - app-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    volumes:
      - redis-data:/data
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
    networks:
      - app-network
    restart: unless-stopped

volumes:
  app-data:
    driver: local
  redis-data:
    driver: local

networks:
  app-network:
    driver: bridge
